// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-FAdmYUXqUjc_P1YeDxdA0SiI_JjgN0',
    appId: '1:1074718473442:web:062156c36106fb6a11f2bb',
    messagingSenderId: '1074718473442',
    projectId: 'zentask-8677d',
    authDomain: 'zentask-8677d.firebaseapp.com',
    storageBucket: 'zentask-8677d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOw_9jaIY1X198p3LGvKGbeDa9IMR-tn4',
    appId: '1:1074718473442:android:c07193cd1d2f4e8e11f2bb',
    messagingSenderId: '1074718473442',
    projectId: 'zentask-8677d',
    storageBucket: 'zentask-8677d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVWzw8YV5Y15y1xZmVyS0ACxeJEsZeR9I',
    appId: '1:1074718473442:ios:da54e20b2b07decc11f2bb',
    messagingSenderId: '1074718473442',
    projectId: 'zentask-8677d',
    storageBucket: 'zentask-8677d.firebasestorage.app',
    iosBundleId: 'com.example.zentask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVWzw8YV5Y15y1xZmVyS0ACxeJEsZeR9I',
    appId: '1:1074718473442:ios:da54e20b2b07decc11f2bb',
    messagingSenderId: '1074718473442',
    projectId: 'zentask-8677d',
    storageBucket: 'zentask-8677d.firebasestorage.app',
    iosBundleId: 'com.example.zentask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7-FAdmYUXqUjc_P1YeDxdA0SiI_JjgN0',
    appId: '1:1074718473442:web:70f9eac940ad5ee811f2bb',
    messagingSenderId: '1074718473442',
    projectId: 'zentask-8677d',
    authDomain: 'zentask-8677d.firebaseapp.com',
    storageBucket: 'zentask-8677d.firebasestorage.app',
  );
}
